name: 'internal-composite-action'
author: 'Benjamin Stepp'
description: 'Is maybe broken?'

runs:
  using: 'composite'
  steps:
    - name: Nested composite action
      shell: bash
      run: |
        echo "This is a big file"

    - uses: ./.github/actions/internal

    - name: Wow many steps
      shell: bash
      run: |
        echo "wow"
