name: 'internal-composite-action'
author: 'Benjamin Stepp'
description: 'Is maybe broken?'

runs:
  using: 'composite'
  steps:
    - name: Gather info
      shell: bash
      id: info
      run: |
        echo "::set-output name=key::broken1"
        echo "::set-output name=path::folder"

    - name: Cache Some Things
      uses: actions/cache@v2
      id: deps-cache
      with:
        path: ${{ steps.info.outputs.path }}
        key: ${{ steps.info.outputs.key }}
