name: Bugged Cache Example

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]


jobs:
  broken:
    name: Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Gather info
        id: info
        run: |
          echo "::set-output name=test::test"

      - name: Cache Some Things
        uses: actions/cache@v2
        id: deps-cache
        with:
          path: folder
          key: ${{ steps.info.outputs.test }}
          restore-keys: |
            ${{ steps.info.outputs.test }}
  works:
    name: Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Some Things
        uses: actions/cache@v2
        id: deps-cache
        with:
          path: folder
          key: test
          restore-keys: |
            test
