name: Bugged Cache Example

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]


jobs:
  broken:
    name: Broken Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/internal

  works:
    name: Working Cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Some Things
        uses: actions/cache@v2
        id: deps-cache
        with:
          path: folder
          key: test
          restore-keys: |
            test
